sudo: required
services:
  - docker

install:
  - docker pull blang/latex:ubuntu

script:
  - ./latexdockercmd.sh bash ./compile-all.sh
  - mkdir dist
  - cp index.html > dist/
  - cp *.pdf > dist/
  - cp *.tex > dist/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: dist
  on:
    branch: master
