sudo: required
services:
  - docker

install:
  - docker pull blang/latex:ubuntu
  - docker save blang/latex:ubuntu | gzip > docker/latex.tar.gz

before_script:
  - gzip -dc docker/latex.tar.gz | docker load

script:
  - ./latexdockercmd.sh bash ./compile-all.sh

cache:
  directories:
  - docker
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: .
  on:
    branch: master
